{{- if .Values.global.service.connector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-props-{{ .Values.global.service.connector.name }}-configmap
  namespace: {{ .Values.global.namespace }}
data:
  application.properties: |-
    kafka.bootstrap.server=broker-service:9092
    kafka.topic.name=twitter-status-json-input
    kafka.application.id=twitter-stream-feeder
    kafka.value.serializer=com.markuvinicius.twitter.stream.serializers.JsonSerializer
    kafka.key.serializer=org.apache.kafka.common.serialization.StringSerializer
    twitter.search.topics=bolsonaro,lula,eleicoes
    twitter.search.languages=pt
{{- end }}
