# Default values for Twitter Processing Application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  namespace: twitter-stream-processing
  prometheusPort: 8088
  imagePullPolicy: IfNotPresent
  pullSecret: regcred
  security:
    kubernetesUserId: 1001
    runAsRoot: true
  service:
    zookeeper:
      name: zookeeper
      port: 2181
      image: confluentinc/cp-zookeeper:5.4.1
      enabled: true
    broker:
      name: broker
      port: 9092
      image: confluentinc/cp-kafka:5.4.1
      enabled: true
    schemaRegistry:
      name: schema-registry
      port: 8081
      image: confluentinc/cp-schema-registry:5.4.1
      enabled: true
    connector:
      name: connector
      image: markuvinicius/twitter-collector:36
      classPath: com.markuvinicius.twitter.stream.Application
      appConfigPath: /config/application.properties
      port: 4040
      enabled: false
    twitterKafkaConnector:
      enabled: true
      name: kafka-connector
      image: markuvinicius/twitter-stream-processing-kafka-connect-worker:0.0.2
      restPort: 30100
      targetPort: 30100
      nodePort: 30100
      replicaCount: 1
      internalTopicsReplicationFactor: 1
#      memory:
#        max: 2Gi
#        min: 1Gi
#      cpu:
#        max: 750m
#        min: 250m
      groupId: kafka-connect-cluster
      storageTopic: kafka-connect-cluster.storage
      offsetTopic: kafka-connect-cluster.offsets
      statusTopic: kafka-connect-cluster.status
      offsetFlushIntervalMs: 35000
      offsetFlushTimeoutMs: 15000
      connectorClientConfigOverridePolicy: All
      keyConverter: org.apache.kafka.connect.storage.StringConverter
      valueConverter: org.apache.kafka.connect.storage.StringConverter
      logLevel: DEBUG
      pluginPath: /usr/share/java,/etc/kafka-connect/jars,/usr/share/confluent-hub-components
      securityProtocol: PLAINTEXT
      topicCreationReplicationFactor: 1
      topicCreationPartitions: 4

